### PR TITLE
Save a CSV

### LINKED ISSUE #1: Improvements and fixes to the saved table
Address the feeback from @kbailey-noaa.

### PR DESCRIPTION
**Pull request by ocefpaf**
- [x] Column A is missing a header-- should be called "dataset_id"
- [x] Sort by column A
- [x] Change date formats to m/dd/yyyy
- [x] Possible to change csv header names? If so, prefer start_date and end_date (instead of time_coverage_start/end), deployment_area (instead of sea_name)
- [x] Days column is populated with timestamps (e.g. 12 days 00:00:00) -- eliminate the timestamp
- [x] Change the column order to: dataset_id, glider, wmo_id, deployment_area, start_date, end_date, days, num_profiles, institution, acknowledgement
- [x] Acknowledgement column has strange values (e.g. Series([], Name: Value, dtype: object)) -- I think this should be populated with "unknown" instead.
- [ ] Possible to prevent the .csv fields from auto-expanding to fit all the text? When I open the .csv the fields with a lot of text expand super wide and it's hard to view

Closes #1

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kbailey-noaa this is how the first 5 rows of the table looks like now. I'm not sure what to do for the last item on your improvement list. We can try to add line breaks but I believe that may look odd in some spreadsheet readers. I believe that we can either make those descriptions shorter (see a few cells below were I fix the `sea_name` and create a mapping for the institution names) or check the spreadsheet reader options to load it without expanding it.

I prefer the former solution but we would need to discuss the mapping first. Mine there was an uneducated first attempt, someone that is more familiar with the institutions can do a better mapping.

| dataset_id          | glider   |   wmo_id | deployment_area      | start_date   | end_date   |   days |   num_profiles | institution                                                                  | acknowledgment                                                                                                                |
|:--------------------|:---------|---------:|:---------------------|:-------------|:-----------|-------:|---------------:|:-----------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------|
| angus-20230526T0051 | angus    |  4802945 | North Atlantic       | 05-26-2023   | 06-12-2023 |     12 |            171 | Skidaway Institute of Oceanography                                           | This deployment is supported by the Office of Naval Research (ONR)                                                            |
| bass-20230610T0000  | bass     |  4801918 | North Atlantic Ocean | 06-11-2023   | 07-06-2023 |     26 |           1257 | University of South Florida College of Marine Science Ocean Technology Group | unknown                                                                                                                       |
| bass-20231007T0000  | bass     |  4801918 | North Atlantic Ocean | 10-07-2023   | 11-06-2023 |     31 |            864 | University of South Florida College of Marine Science Ocean Technology Group | unknown                                                                                                                       |
| bill-20230802T1140  | bill     |  4803970 | Long Island Sound    | 08-02-2023   | 08-24-2023 |     23 |          12969 | University of Connecticut                                                    | This deployment is supported by United States Environmental Protection Agency and the U.S. Integrated Ocean Observing System. |
| bill-20230907T1530  | bill     |  4803970 | Long Island Sound    | 09-07-2023   | 09-09-2023 |      3 |           1123 | University of Connecticut                                                    | This deployment is supported by United States Environmental Protection Agency and the U.S. Integrated Ocean Observing System. |

**Comment by ocefpaf** [comment]
BTW, the [OSU685-20231023T0000](https://gliders.ioos.us/erddap/tabledap/OSU685-20231023T0000.html) seems to be problematic. You had issues with it yesterday and I had a few today. Sometimes the data is not there altogether, sometimes it is incomplete. See the image below where I captured a state where nothing was there. That particular glider is not in this list but it could be related to https://github.com/ioos/glider-dac/issues/338.

Screenshot from 2024-05-01 16-22-02

I coded a workaround so the metrics notebook will complete regardless. That can lead to incomplete metrics if/when the missing data is back online. The notebook will print warnings when that happens so we can investigate.

**Comment by kbailey-noaa** [comment]
Excellent!  The output you pasted here looks great.  It's not worth agonizing over the cell width issues - that is a minor inconvenience. I'll try to run the notebook today.

**Comment by kbailey-noaa** [comment]
Also - I looked at that problematic OSU dataset and got ht esame error you did when I first opened the link.  But then ever since it has loaded fine.  Is there a repeatable issue I can submit via glider-dac repo?  I believe this is different from https://github.com/ioos/glider-dac/issues/338 because the latter is specific to datasets that are missing from ERDDAP altogether.

**Comment by ocefpaf** [comment]
> Or perhaps you could submit an issue?

I'll do that. I just realized I noticed this problem last month and forgot to report.

**Comment by kbailey-noaa** [comment]
Tested and it looks great!  Ignore the column width thing - I can easily adjust the column width on my end. No need to hardcode anything.  Consider this completed!

**Pull request merged**
